// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionAside: typeof import('./components/layouts/ActionAside.vue')['default']
    Background: typeof import('./components/template/Background.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    CodeContainer: typeof import('./components/layouts/CodeContainer.vue')['default']
    CodeDialog: typeof import('./components/layouts/CodeDialog.vue')['default']
    ConfigForm: typeof import('./components/layouts/ConfigForm.vue')['default']
    Container: typeof import('./components/template/Container.vue')['default']
    ContentMain: typeof import('./components/layouts/ContentMain.vue')['default']
    DragAside: typeof import('./components/layouts/DragAside.vue')['default']
    Edit: typeof import('./components/layouts/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./components/template/Header.vue')['default']
    Image: typeof import('./components/template/Image.vue')['default']
    ListDialog: typeof import('./components/layouts/ListDialog.vue')['default']
    PsdDialog: typeof import('./components/layouts/PsdDialog.vue')['default']
    QrCode: typeof import('./components/template/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./components/template/Text.vue')['default']
  }
}

export {}
