// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    ConfigForm: typeof import('./components/layouts/ConfigForm.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    ContentMain: typeof import('./components/layouts/ContentMain.vue')['default']
    Edit: typeof import('./components/layouts/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Header: typeof import('./components/Header.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    LeftAside: typeof import('./components/layouts/LeftAside.vue')['default']
    QrCode: typeof import('./components/QrCode.vue')['default']
    RightAside: typeof import('./components/layouts/RightAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./components/Text.vue')['default']
  }
}

export {}
